version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            python --version
            cp yarn.lock orig-yarn-lock-file
            yarn
            yarn cache dir
      - run:
          name: Lint
          command: yarn lint:ci
      - run:
          name: Test
          command: yarn test:ci
      - run:
          name: Build size
          command: yarn test:size
      