version: 2
jobs:
  build:
    docker:
       - image: circleci/node:10.12.0
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Install deps
          command: |
            python --version
            cp yarn.lock orig-yarn-lock-file
            yarn
            yarn cache dir 
      - run:
          name: Lint
          command: yarn lint:ci          
      - run:
          name: Test
          command: yarn test:ci    
         